name: Clone Repository

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destino
        uses: actions/checkout@v3

      - name: Clone o repositório de origem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |   
          git clone --mirror https://$GITHUB_TOKEN@github.com/tatihav/profalisson.git
          cd profalisson.git
          git push --mirror https://$GITHUB_TOKEN@github.com/alissonzkv/alissonzkv.github.io.git
