name: Clone Repository

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destino
        uses: actions/checkout@v3

      - name: Clone o repositório de origem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --bare https://https://github.com/tatihav/profalisson.git repo-clone.git
          cd repo-clone.git
          git push --mirror https://github.com/alissonzkv/alissonzkv.github.io.git
