name: Clone Repository

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git para usar o GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Clone o repositório de origem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --mirror https://${GITHUB_TOKEN}@github.com/tatihav/profalisson.git profalisson.git
          cd profalisson.git
          git push --mirror https://${GITHUB_TOKEN}@github.com/alissonzkv/alissonzkv.github.io.git
