name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Executa o workflow quando há push na branch master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          submodules: false  # Ignora submódulos, se existirem

      - name: Force remove 'profalisson' directory
        run: |
          if [ -d "profalisson" ]; then
            rm -rf profalisson
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Escolha a versão de Node.js compatível com seu projeto

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Certifique-se de que este é o comando correto para build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Altere para o diretório correto, se não for 'build'
